version: '3.1'
# Servicios
services:

  reverse-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: Reverse-Proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - VIRTUAL_HOST=portal-saul.ddns.net
      - VIRTUAL_PATH=/.well-known
    volumes:
      - /volumes/nginx/certs:/etc/nginx/certs:ro
      - /volumes/nginx/vhostd:/etc/nginx/vhost.d
      - /volumes/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro

  lets-encrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: 'Lets-Encrypt'
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=Reverse-Proxy
    volumes:
      - /volumes/nginx/certs:/etc/nginx/certs
      - /volumes/nginx/vhostd:/etc/nginx/vhost.d
      - /volumes/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  portal:
    image: nginx
    restart: always
    environment:
      - VIRTUAL_HOST=portal-saul.ddns.net
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=portal-saul.ddns.net
      - LETSENCRYPT_EMAIL=saul_romo@hotmail.com
    volumes:
      - /volumes/www/portal:/usr/share/nginx/html:ro

  factura:
    image: nginx
    restart: always
    environment:
      - VIRTUAL_HOST=portal-saul.ddns.net
      - VIRTUAL_PATH=/facturas
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=portal-saul.ddns.net
      - LETSENCRYPT_EMAIL=saul_romo@hotmail.com
    volumes:
      - /volumes/www/factura:/usr/share/nginx/html:ro

  erp:
    image: httpd
    restart: always
    environment:
      - VIRTUAL_HOST=portal-saul.ddns.net
      - VIRTUAL_PATH=/erp
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=portal-saul.ddns.net
      - LETSENCRYPT_EMAIL=saul_romo@hotmail.com
    volumes:
      - /volumes/www/erp:/usr/local/apache2/htdocs