version: '3.1'
# Servicios
services:

  portal:
    image: nginx
    container_name: Portal
    restart: always
    ports:
      - 80:80
      - 443:443 
    environment:
      - VIRTUAL_HOST=portal-saul.ddns.net
    volumes:
      - /volumes/www/portal:/usr/share/nginx/html:ro

  